[package]
edition = "2021"
name = "haxial-kl"
description = "An open source implementation of Haxial KL"
version = "0.1"

[features]
default = []

[dependencies]
bitflags = "1.3.2"
nom = "7.1.1"
thiserror = "1.0.31"
